### PR TITLE
Add GIF to README

### PR DESCRIPTION
**Pull request by mitmul**
People like GIF animation.
People like moving stuff.
People like to see the experimental results at the top of README.

### CODE REVIEW

**Comment by rezoo** [comment]
It seems that this GIF is not displayed on the top page due to the content length. Can you check this?

**Comment by mitmul** [comment]
@rezoo Thank you for pointing out it. I resized the GIF image.

**Comment by rezoo** [comment]
Thank you! As with chainer-LSGAN, can you insert the image after the disclaimer, and add "Results" section?

**Comment by mitmul** [comment]
Sure. fixed.

**Comment by rezoo** [comment]
LGTM.

**Pull request merged**
